[project]
name = "fs_analyzer"
version = "0.1.0"
description = "A command-line tool for analyzing the file system."

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]